version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    profiles: [ all, backend ]
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "p@ssw0rd"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "p@ssw0rd", "-Q", "SELECT 1" ]
      interval: 15s
      timeout: 30s
      retries: 3
      start_period: 60s
    volumes:
     - D:/Volumes/sqlserver:/var/opt/mssql/data
  
  eventbus:
    image: rabbitmq:3-management
    profiles: [ all, eventbus, backend ]
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: p@ssw0rd
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 30s
      retries: 3
      start_period: 60s

  frontend:
    image: ${DOCKER_REGISTRY-}frontend:latest
    profiles: [ all, frontend ]
    depends_on:
     - dashboardservice
     - tileservice
     - dataconsumerservice
     - uiinfoservice
    ports:
      - "5500:80/tcp"

  dashboardservice:
    image: ${DOCKER_REGISTRY-}dashboardservice:latest
    profiles: [ all, backend ]
    build:
      context: .
      dockerfile: TheDashboard.DashboardService/Dockerfile
    ports:
      - "5100:80/tcp"
    depends_on:
      - sqlserver
      - eventbus
  
  tileservice:
    image: ${DOCKER_REGISTRY-}tileservice
    profiles: [ all, backend ]
    build:
      context: .
      dockerfile: TheDashboard.TileService/Dockerfile
    ports:
      - "5200:80/tcp"
    depends_on:
      - sqlserver
      - eventbus

  dataconsumerservice:
    image: ${DOCKER_REGISTRY-}dataconsumerservice
    profiles: [ all, backend ]
    build:
      context: .
      dockerfile: TheDashboard.DataConsumerService/Dockerfile
    ports:
      - "5300:80/tcp"
    depends_on:
      - sqlserver
      - eventbus

  uiinfoservice:
    image: ${DOCKER_REGISTRY-}uiinfoservice
    profiles: [ all, backend ]
    build:
      context: .
      dockerfile: TheDashboard.UiInfoservice/Dockerfile
    ports:
      - "5400:80/tcp"
    depends_on:
      - sqlserver
      - eventbus

volumes:
  sqlserver: ~
